### ISSUE TITLE
Parent menu item is not clickable to open page

### ISSUE THREAD

**Issue by cmwwebfx** [SimonPadbury/bst-plus#14]
Hi Simon,

Could you advise an option that I can have the parent menu item be a clickable link to open a page. Right now the theme seems to make a parent menu item only trigger an open for the child menus.

Thank you.

**Comment by SimonPadbury** [comment]
Hi Ciaran,
Normally, Bootstrap navbar parent links don't work as links -- because they immobilized the normal link behaviour somewhere in the Bootstrap JS code. Instead, clicking a parent menu item opens a dropdown menu.

You could override that code by using putting this into the BST-Plus jQuery below (wait - read on before you try it):

OPTION 1:

$('.navbar .dropdown > a').click(function() {
    location.href = this.href;});
It works, but there is a problem with doing that -- because of what happens on phones. On phones you want to tap the parent and have the dropdown menu become open -- and this still happens. So on phones the dropdown appears and, a few seconds later (depending on internet connection speed), the visitor gets whipped away to linked page anyway.

OPTION 2:
$('.hovernav .dropdown-toggle').click(function() {
    location.href = this.href;});
Place this anywhere in js/bst-plus.js -- it doesn't matter where, anywhere inside the document.ready function.

Notice that this will only function at width 768px up, because the .hovernav class is not inserted for screen widths below that.
So use OPTION 2 -- it does **almost** everything you're asking for. What you are asking for isn't compatible with the navbar operation on phones anyway.

Simon
