### ISSUE TITLE
Walker_Nav_Menu

### ISSUE THREAD

**Issue by Jim-E** [SimonPadbury/bst-plus#4]
I get this error when installing theme:

````

Strict Standards: Declaration of BootstrapNavMenuWalker::start_lvl() should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in D:\Dev\eztd.dev\wp-content\themes\bst-plus-master\functions\navbar.php on line 109

````

Thanks

**Comment by SimonPadbury** [comment]
Hi Jim,

Sorry, its all working fine for me in a local WP install (I just downloaded the bst-plus currently on GitHub). I'm not seeing the error. In what software are you seeing this error?

Your error message points to: functions/navbar.php - line 109  -- but that line is a is a // comment

**Comment by Jim-E** [comment]
Sorry about this but I forgot that I had removed some comments because the error led to a }, the actual error is on line 120.
````
Strict Standards: Declaration of BootstrapNavMenuWalker::start_lvl() should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in /home/eztdvnet/public_html/wp-content/themes/bst-plus-master/functions/navbar.php on line 120
````

I just did a fresh local install with ServerPress DesktopServer (Xampp), and a fresh install on a live server, both Wordpress v4.1, both, same message.

I have wp-config.php debug on:
````
define('WP_DEBUG', true);
````

**Comment by SimonPadbury** [comment]
I have AMPSS server (on a Mac), running WordPress 4.1, with WP_DEBUG set to true, same as you. Sorry I'm still not seeing this error. Plus I've tried the theme on a live website, where I also don't see the error. And it's working for me, whether or not I put a menu in

I did just do some other tidying up (I noticed that the comments weren't working properly; they are now).

Can you try using my BST theme (it has the same base files, including functions/navbar.php). Do you get the same error message?

**Comment by Jim-E** [comment]
Still doing it, I do have the Wordpress Theme Unit Test imported:

https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml

**Comment by SimonPadbury** [comment]
That Extended Walker was something I coped (without alteration) from a Gist. I can't figure out why it's now throwing an error. I just checked the same Gist and I see that it has been updated since I copied it a couple of years ago. [https://gist.github.com/setola/3765640](https://gist.github.com/setola/3765640)

OK, I have swapped the Extended Walker on functions/navbar.php for that newer version. And it still works for me on my local server install of BST-Plus. *Can you try again*?

And can you try using my BST [https://github.com/SimonPadbury/bst](https://github.com/SimonPadbury/bst)? Currently it still has the earlier Extended Walker. If the newer version gives you no errors I will swap this too.

**Comment by Jim-E** [comment]
Same message except now it's line 116.

**Comment by SimonPadbury** [comment]
I can't figure this out, sorry. The error is still not showing for me. I can't see any problems with header.php, index.php or navbar.php
